
INSERT INTO COURSES (NAME, DURATION, FEE, PREREQUISITE)
VALUES('ORACLE',25,4500,'WINDOWS'),
	  ('VB.NET',30,5500,'WINDOWS AND PROGRAMMING'),
	  ('C PROGRAMMING',20,3500,'COMPUTER AWARENESS'),
	  ('ASP.NET',25,5000,'INTERNET AND PROGRAMMING'),
	  ('JAVA LANGUAGE',25,4500,'C LANGUAGE'),
	  ('XML PROGRAMMING', 15, 4000, 'HTML,SCRIPTING ASP/JSP');

SELECT * FROM COURSES;



INSERT INTO FACULTY (NAME, QUAL, EXP)
VALUES('GEORGE KOCH','MS COMPUTER SCIENCE','15 YEARS WITH DATABASES'),
	  ('DAN APPLEMAN','CS AND EE GRADUATE', 'EXTENSIVELY WORKED WITH COM'),
	  ('HERBERT SCHILDT','MS COMPUTER SCIENCE', 'AUTHOR OF SEVERAL BOOKS'),
	  ('DAVID HUNTER','MS ELECTRONICS', 'EXTENSIVELY WORKED WITH INTERNET TEHNOLOGEES'),
	  ('STEPHEN WALTHER','PH.D. IN PHILOSOPHY', 'EXTENSIVELY WORKED WITH INTERNET TEHNOLOGEES'),
	  ('KEVIN LONEY', 'MS ELETRONICS', 'SPECIALIZED IN ORACLE DBA'),
	  ('JAMIE JAWORSKI','BACHLORS OF ELECTRICAL' ,'DEVELOPED PROGRAMS FOR US DEFENSE DEPARTMENT'),
	  ('JASON COUCHMAN','OCP DBA','PUBLISHED ARTICLES ON ORACLE');

SELECT * FROM FACULTY;



INSERT INTO COURSE_FACULTY (FACCODE, CCODE, GRADE)
 VALUES(1,2,'A'),
	   (1,1,'A'),
	   (2,1,'A'),
	   (2,2,'A'),
	   (3,5,'A'),
       	   (5,6,'B'),
	   (4,5,'A'),
           (5,4,'A'),
           (3,1,'A'),
           (4,3,'B'),
           (2,5,'A'),
           (3,6,'B');                         

SELECT * FROM COURSE_FACULTY;

