CREATE TABLE COURSES
(
    CCODE INT AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    DURATION INT NOT NULL CHECK(DURATION >= 1),
    FEE INT NOT NULL CHECK(FEE >= 0),
    PREREQUISITE VARCHAR(100) NOT NULL,
    PRIMARY KEY(CCODE)
);

DESC COURSES;


CREATE TABLE FACULTY
(
    FACCODE INT AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    QUAL VARCHAR(30) NOT NULL,
    EXP VARCHAR(100) NOT NULL,
    PRIMARY KEY(FACCODE)
);

DESC FACULTY;

CREATE TABLE COURSE_FACULTY
(
	FACCODE INT NOT NULL,
	CCODE INT NOT NULL,
	GRADE CHAR(1) NOT NULL,
	FOREIGN KEY(FACCODE) REFERENCES FACULTY(FACCODE),
	FOREIGN KEY(CCODE) REFERENCES COURSES(CCODE),
	PRIMARY KEY(FACCODE,CCODE),
    	CONSTRAINT FACULTY_GRADE CHECK (GRADE IN ('A','B','C'))
);

DESC COURSE_FACULTY;
